services:
  bitwarden-alias-provider-server:
    container_name: bitwarden-alias-provider-server
    image: ghcr.io/bfpimentel/bitwarden-alias-provider-server:latest
    env_file: .env
    ports:
      - "6123:6123"
  bitwarden-alias-provider-web:
    container_name: bitwarden-alias-provider-web
    image: ghcr.io/bfpimentel/bitwarden-alias-provider-web:latest
    env_file: .env
    ports:
      - "6124:6124"
    depends_on:
      - bitwarden-alias-provider-server
